name: "Collect Ranges"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: collector
      run: |
          php -S localhost:8080 index.php
          git config --global user.email "ircfspace@gmail.com"
          git config --global user.name "ircfspace"
          git add -A
          git commit -m "Automatic update"
          git push
