name: "Collect Ranges"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Collect Ranges
        run: |
          php index.php
          git config --global user.email "ircfspace@gmail.com"
          git config --global user.name "ircfspace"
          git config credential.helper store
          git add -A
          git commit -m "Automatic Update"
          git push
